package com.hcteol.jwt.backend.services;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.hcteol.jwt.backend.dtos.PurchaseOrderDto;
import com.hcteol.jwt.backend.dtos.PurchaseOrderItemDto;
import com.hcteol.jwt.backend.entities.PurchaseOrder;
import com.hcteol.jwt.backend.entities.PurchaseOrderItem;
import com.hcteol.jwt.backend.repositories.PurchaseOrderItemRepository;
import com.hcteol.jwt.backend.repositories.PurchaseOrderRepository;

@Service
public class PurchaseOrderService {

    @Autowired
    private PurchaseOrderRepository purchaseOrderRepository;

    @Autowired
    private PurchaseOrderItemRepository purchaseOrderItemRepository;

    /**
     * Create a new purchase order with its items
     */
    @Transactional
    public PurchaseOrderDto createPurchaseOrder(PurchaseOrderDto purchaseOrderDto) {
        // Save the purchase order first
        // If orderId is null, it will be auto-generated by the database
        PurchaseOrder purchaseOrder = PurchaseOrder.builder()
                .orderId(purchaseOrderDto.getOrderId())
                .vendorId(purchaseOrderDto.getVendorId())
                .orderDate(purchaseOrderDto.getOrderDate())
                .purchaseAmount(purchaseOrderDto.getPurchaseAmount())
                .orderStatus(purchaseOrderDto.getOrderStatus() != null ? purchaseOrderDto.getOrderStatus() : "NEW")
                .build();

        PurchaseOrder savedOrder = purchaseOrderRepository.save(purchaseOrder);

        // Save the order items with generated itemId
        List<PurchaseOrderItem> items = new ArrayList<>();
        if (purchaseOrderDto.getItems() != null && !purchaseOrderDto.getItems().isEmpty()) {
            for (int i = 0; i < purchaseOrderDto.getItems().size(); i++) {
                PurchaseOrderItemDto itemDto = purchaseOrderDto.getItems().get(i);
                String itemId = savedOrder.getOrderId() + "_" + (i + 1);
                
                PurchaseOrderItem item = PurchaseOrderItem.builder()
                        .itemId(itemId)
                        .orderId(savedOrder.getOrderId())
                        .itemType(itemDto.getItemType())
                        .productCode(itemDto.getProductCode())
                        .internalProductCode(itemDto.getInternalProductCode())
                        .internalOrderId(itemDto.getInternalOrderId())
                        .quantity(itemDto.getQuantity())
                        .unitPrice(itemDto.getUnitPrice())
                        .lineTotal(itemDto.getLineTotal())
                        .build();
                
                items.add(purchaseOrderItemRepository.save(item));
            }
        }

        return convertToDto(savedOrder, items);
    }

    /**
     * Get all purchase orders
     */
    public List<PurchaseOrderDto> getAllPurchaseOrders() {
        List<PurchaseOrder> orders = purchaseOrderRepository.findAll();
        return orders.stream()
                .map(order -> {
                    List<PurchaseOrderItem> items = purchaseOrderItemRepository.findByOrderId(order.getOrderId());
                    return convertToDto(order, items);
                })
                .collect(Collectors.toList());
    }

    /**
     * Get a purchase order by ID
     */
    public PurchaseOrderDto getPurchaseOrderById(String orderId) {
        PurchaseOrder order = purchaseOrderRepository.findById(orderId)
                .orElseThrow(() -> new RuntimeException("Purchase Order not found with id: " + orderId));
        
        List<PurchaseOrderItem> items = purchaseOrderItemRepository.findByOrderId(orderId);
        return convertToDto(order, items);
    }

    /**
     * Get purchase orders by vendor ID
     */
    public List<PurchaseOrderDto> getPurchaseOrdersByVendorId(Long vendorId) {
        List<PurchaseOrder> orders = purchaseOrderRepository.findByVendorId(vendorId);
        return orders.stream()
                .map(order -> {
                    List<PurchaseOrderItem> items = purchaseOrderItemRepository.findByOrderId(order.getOrderId());
                    return convertToDto(order, items);
                })
                .collect(Collectors.toList());
    }

    /**
     * Get purchase orders by status
     */
    public List<PurchaseOrderDto> getPurchaseOrdersByStatus(String orderStatus) {
        List<PurchaseOrder> orders = purchaseOrderRepository.findByOrderStatus(orderStatus);
        return orders.stream()
                .map(order -> {
                    List<PurchaseOrderItem> items = purchaseOrderItemRepository.findByOrderId(order.getOrderId());
                    return convertToDto(order, items);
                })
                .collect(Collectors.toList());
    }

    /**
     * Update a purchase order
     */
    @Transactional
    public PurchaseOrderDto updatePurchaseOrder(String orderId, PurchaseOrderDto purchaseOrderDto) {
        PurchaseOrder existingOrder = purchaseOrderRepository.findById(orderId)
                .orElseThrow(() -> new RuntimeException("Purchase Order not found with id: " + orderId));

        // Update order fields
        existingOrder.setVendorId(purchaseOrderDto.getVendorId());
        existingOrder.setOrderDate(purchaseOrderDto.getOrderDate());
        existingOrder.setPurchaseAmount(purchaseOrderDto.getPurchaseAmount());
        existingOrder.setOrderStatus(purchaseOrderDto.getOrderStatus());

        PurchaseOrder updatedOrder = purchaseOrderRepository.save(existingOrder);

        // Delete existing items and create new ones
        purchaseOrderItemRepository.deleteByOrderId(orderId);

        List<PurchaseOrderItem> items = new ArrayList<>();
        if (purchaseOrderDto.getItems() != null && !purchaseOrderDto.getItems().isEmpty()) {
            for (int i = 0; i < purchaseOrderDto.getItems().size(); i++) {
                PurchaseOrderItemDto itemDto = purchaseOrderDto.getItems().get(i);
                String itemId = orderId + "_" + (i + 1);
                
                PurchaseOrderItem item = PurchaseOrderItem.builder()
                        .itemId(itemId)
                        .orderId(orderId)
                        .itemType(itemDto.getItemType())
                        .productCode(itemDto.getProductCode())
                        .internalProductCode(itemDto.getInternalProductCode())
                        .internalOrderId(itemDto.getInternalOrderId())
                        .quantity(itemDto.getQuantity())
                        .unitPrice(itemDto.getUnitPrice())
                        .lineTotal(itemDto.getLineTotal())
                        .build();
                
                items.add(purchaseOrderItemRepository.save(item));
            }
        }

        return convertToDto(updatedOrder, items);
    }

    /**
     * Delete a purchase order and its items
     */
    @Transactional
    public void deletePurchaseOrder(String orderId) {
        if (!purchaseOrderRepository.existsById(orderId)) {
            throw new RuntimeException("Purchase Order not found with id: " + orderId);
        }
        
        // Delete all items first
        purchaseOrderItemRepository.deleteByOrderId(orderId);
        
        // Delete the order
        purchaseOrderRepository.deleteById(orderId);
    }

    /**
     * Update order status
     */
    @Transactional
    public PurchaseOrderDto updateOrderStatus(String orderId, String newStatus) {
        PurchaseOrder order = purchaseOrderRepository.findById(orderId)
                .orElseThrow(() -> new RuntimeException("Purchase Order not found with id: " + orderId));
        
        order.setOrderStatus(newStatus);
        PurchaseOrder updatedOrder = purchaseOrderRepository.save(order);
        
        List<PurchaseOrderItem> items = purchaseOrderItemRepository.findByOrderId(orderId);
        return convertToDto(updatedOrder, items);
    }

    /**
     * Helper method to convert entities to DTO
     */
    private PurchaseOrderDto convertToDto(PurchaseOrder order, List<PurchaseOrderItem> items) {
        List<PurchaseOrderItemDto> itemDtos = items.stream()
                .map(item -> PurchaseOrderItemDto.builder()
                        .itemId(item.getItemId())
                        .orderId(item.getOrderId())
                        .itemType(item.getItemType())
                        .productCode(item.getProductCode())
                        .internalProductCode(item.getInternalProductCode())
                        .internalOrderId(item.getInternalOrderId())
                        .quantity(item.getQuantity())
                        .unitPrice(item.getUnitPrice())
                        .lineTotal(item.getLineTotal())
                        .build())
                .collect(Collectors.toList());

        return PurchaseOrderDto.builder()
                .orderId(order.getOrderId())
                .vendorId(order.getVendorId())
                .orderDate(order.getOrderDate())
                .purchaseAmount(order.getPurchaseAmount())
                .orderStatus(order.getOrderStatus())
                .items(itemDtos)
                .build();
    }
}
