CREATE TABLE IF NOT EXISTS delivery_return (
    return_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    do_id VARCHAR(255) NOT NULL,
    return_date TIMESTAMP,
    return_status VARCHAR(50),
    returned_by VARCHAR(255),
    location VARCHAR(255),
    total_quantity INTEGER
);

CREATE TABLE IF NOT EXISTS delivery_return_item (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_code VARCHAR(255),
    stock_code VARCHAR(255),
    quantity INTEGER
);
