CREATE TABLE IF NOT EXISTS stock_disposal (
    disposal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location VARCHAR(255),
    disposed_by VARCHAR(255),
    disposal_date TIMESTAMP,
    disposal_reason VARCHAR(255),
    disposal_method VARCHAR(255),
    disposal_status VARCHAR(50),
    total_quantity INTEGER
);

CREATE TABLE IF NOT EXISTS stock_disposal_item (
    stock_disposal_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disposal_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_code VARCHAR(255),
    stock_code VARCHAR(255),
    quantity INTEGER
);
