CREATE TABLE project_block (
    project_block_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code VARCHAR(255) NOT NULL,
    block_name VARCHAR(255),
    block_description TEXT,
    block_number BIGINT NOT NULL,
    status VARCHAR(50),
    CONSTRAINT uk_project_block_project_code_block_number UNIQUE (project_code, block_number),
    CONSTRAINT fk_project_block_project_code FOREIGN KEY (project_code) REFERENCES project (project_code) ON DELETE CASCADE
);

CREATE TABLE project_storey (
    project_storey_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_block_id BIGINT NOT NULL,
    storey_name VARCHAR(255),
    storey_description TEXT,
    storey_number BIGINT NOT NULL,
    status VARCHAR(50),
    CONSTRAINT uk_project_storey_block_storey_number UNIQUE (project_block_id, storey_number),
    CONSTRAINT fk_project_storey_project_block FOREIGN KEY (project_block_id) REFERENCES project_block (project_block_id) ON DELETE CASCADE
);

CREATE TABLE project_unit (
    project_unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_storey_id BIGINT NOT NULL,
    unit_name VARCHAR(255),
    unit_description TEXT,
    unit_number BIGINT NOT NULL,
    project_stream_id BIGINT,
    status VARCHAR(50),
    CONSTRAINT uk_project_unit_storey_unit_number UNIQUE (project_storey_id, unit_number),
    CONSTRAINT uk_project_unit_project_stream_id UNIQUE (project_stream_id),
    CONSTRAINT fk_project_unit_project_storey FOREIGN KEY (project_storey_id) REFERENCES project_storey (project_storey_id) ON DELETE CASCADE,
    CONSTRAINT fk_project_unit_project_stream FOREIGN KEY (project_stream_id) REFERENCES project_stream (project_stream_id) ON DELETE SET NULL
);

CREATE TABLE project_unit_work (
    project_unit_work_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_unit_id BIGINT NOT NULL,
    project_task_id BIGINT,
    work_name VARCHAR(255),
    status VARCHAR(50),
    CONSTRAINT uk_project_unit_work_unit_task UNIQUE (project_unit_id, project_task_id),
    CONSTRAINT fk_project_unit_work_project_unit FOREIGN KEY (project_unit_id) REFERENCES project_unit (project_unit_id) ON DELETE CASCADE,
    CONSTRAINT fk_project_unit_work_project_task FOREIGN KEY (project_task_id) REFERENCES project_task (project_task_id) ON DELETE SET NULL
);