CREATE TABLE IF NOT EXISTS project_stack (
    project_stack_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_block_id BIGINT NOT NULL,
    stack_name VARCHAR(255),
    stack_description TEXT,
    stack_number BIGINT NOT NULL,
    status VARCHAR(50),
    CONSTRAINT uk_project_stack_block_stack_number UNIQUE (project_block_id, stack_number),
    CONSTRAINT fk_project_stack_project_block FOREIGN KEY (project_block_id) REFERENCES project_block (project_block_id) ON DELETE CASCADE
);

ALTER TABLE project_unit
    ADD COLUMN IF NOT EXISTS project_stack_id BIGINT;

ALTER TABLE project_unit
    DROP CONSTRAINT IF EXISTS fk_project_unit_project_stack;

ALTER TABLE project_unit
    ADD CONSTRAINT fk_project_unit_project_stack
        FOREIGN KEY (project_stack_id) REFERENCES project_stack (project_stack_id) ON DELETE CASCADE;

ALTER TABLE project_unit
    DROP CONSTRAINT IF EXISTS uk_project_unit_storey_stack;

ALTER TABLE project_unit
    ADD CONSTRAINT uk_project_unit_storey_stack UNIQUE (project_storey_id, project_stack_id);
