CREATE TABLE IF NOT EXISTS purchase_return (
    return_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id VARCHAR(255) NOT NULL,
    return_date TIMESTAMP,
    return_status VARCHAR(50),
    returned_by VARCHAR(255),
    vendor_id BIGINT,
    location VARCHAR(255),
    total_quantity INTEGER,
    credit_amount DECIMAL(19, 4)
);

CREATE TABLE IF NOT EXISTS purchase_return_item (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_code VARCHAR(255),
    stock_code VARCHAR(255),
    quantity INTEGER,
    unit_price DECIMAL(19, 4),
    line_total DECIMAL(19, 4)
);
